name: Unit-tests on Macos CPU

on:
  pull_request:
  push:
    branches:
      - nightly
      - main
      - release/*
  workflow_dispatch:

env:
  CHANNEL: "nightly"

jobs:
  tests:
    uses: pytorch/test-infra/.github/workflows/macos_job.yml@main
    with:
      runner: macos-12
      repository: pytorch/torchcodec
      timeout: 180
      script: |
        set -euxo pipefail
        whoami
        pwd
        ls

        build_tests_dir="${PWD}/build_tests"
        mkdir $build_tests_dir
        pushd $build_tests_dir
        TORCH_PATH=$(python -c "import pathlib, torch; print(pathlib.Path(torch.__path__[0]))")
        Torch_DIR="${TORCH_PATH}/share/cmake/Torch"
        cmake .. -DTorch_DIR=$Torch_DIR -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTS=ON -DCMAKE_VERBOSE_MAKEFILE=ON
        cmake --build .
        ctest
        popd
